// backend/main.c
#include "JaFA.tab.h" // generated by bison -d
#include "jafa_compiler.h"
#include <stdio.h>

extern void init_buffers();
extern void print_final_output();

int main() {
  init_buffers();
  yyparse();
  print_final_output();
  return 0;
}
